# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/bionic64"
    ubuntu.vm.network "private_network", type: "dhcp"
    ubuntu.vm.synced_folder "./data-ubuntu", "/vagrant_data", create: true
    ubuntu.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y ansible vim
    SHELL
  end
  config.vm.define "centos" do |centos|
    # We are going to use unofficial image, because official one does not contain
    # VirtualBox Guest Additions required to set network and synced folder 
    centos.vm.box = "geerlingguy/centos7"
    #centos.vm.box = "centos/7"
    centos.vm.synced_folder "./data-centos", "/vagrant_data", create: true
    centos.vm.provision "shell", inline: <<-SHELL
      yum -y install vim 
    SHELL
  end
end
