- hosts: all
  user: vagrant
  become: yes
  tasks:
    - debug: msg="{{inventory_hostname}}"
  roles:
    - role: mycooltools
    - role: webserver
      tags:
        - webserver
    - role: helloworldpage
      tags:
        - helloworldpage
 
