---

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: test-role-vagrant-01
    box: centos/7
    box_version: "1804.02"
    memory: 512
    cpus: 1

provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: False

scenario:
  name: vagrant

lint:
  name: yamllint
  enabled: False

#verifier:
#  name: testinfra
#  lint:
#    name: flake8
